# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: fetch news

on:
  schedule:
    - cron: '0 */1  * * *'  # 每天隔1小时运行一次
  workflow_dispatch:  # 允许手动触发工作流

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r news_spider/requirements.txt
    - name: Tailscale
      uses: tailscale/github-action@v3
      with:
        oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
        oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
        tags: tag:ci
    - name: run crawler
      run: |
        python workflows/news_crawler.py --db-type postgresql --pg-host ${{ secrets.DB_HOST }} --pg-database ${{ secrets.DB_DATABASE }} --pg-user ${{ secrets.DB_USER }}  --pg-password ${{ secrets.DB_PASSWD }} 
      env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWD: ${{ secrets.DB_PASSWD }}
          DB_DATABASE: ${{ secrets.DB_DATABASE }}
